import type { LandingConfig } from './_template';

export const landingConfigs: Record<string, LandingConfig> = {
  'peanut-allergy-app': {
    slug: 'peanut-allergy-app',
    title: 'Peanut Allergy App | My SafetyZone — AI Allergen Scanner & EpiPen Tracker',
    metaDescription: 'The #1 peanut allergy app for iOS. AI-powered peanut detection in menus and recipes, QR allergy cards in 200+ languages, EpiPen expiration tracker, and FDA recall alerts. Free download.',
    h1: 'The #1 Peanut Allergy App',
    h1Accent: 'for iOS.',
    keyword: 'peanut allergy app',
    audience: 'people with peanut allergies, parents of kids with peanut allergies, and adults managing anaphylactic peanut allergies',
    intro: "Living with a peanut allergy means every meal is a calculation. My SafetyZone takes the guesswork out — AI-powered peanut detection across menus, recipes, and ingredient lists, plus a QR allergy card you can show any restaurant, anywhere in the world.",
    benefits: [
      { title: 'AI peanut detection', body: 'Scan menus, recipes, and ingredients with AI that flags peanuts, peanut oil, peanut flour, and hidden derivatives like arachis oil.' },
      { title: 'QR allergy card in 200+ languages', body: 'One scan and any restaurant — domestic or international — knows you have a peanut allergy in their native language.' },
      { title: 'EpiPen expiration tracker', body: 'Never carry an expired epinephrine auto-injector again. Auto-reminders before each EpiPen expires.' },
      { title: 'FDA recall alerts', body: 'Real-time notifications when products are recalled for undeclared peanut content.' },
    ],
    faqs: [
      { q: 'How does My SafetyZone detect peanuts?', a: 'My SafetyZone uses AI trained on FDA allergen databases and ingredient derivative lists to flag peanuts, peanut protein, peanut oil, peanut flour, arachis oil, mandelonas, and other hidden peanut sources in menus, recipes, and packaged foods.' },
      { q: 'Is My SafetyZone good for kids with peanut allergies?', a: 'Yes. Parents can build allergy profiles for each child, generate QR allergy cards for school and daycare staff, and track every EpiPen expiration date in one place.' },
      { q: 'Does it work for tree nut allergies too?', a: 'Yes. My SafetyZone supports peanuts and all tree nuts (almonds, cashews, walnuts, pecans, pistachios, macadamia, Brazil nuts, hazelnuts), plus 50+ other allergens and dietary needs.' },
      { q: 'Is My SafetyZone free?', a: 'Yes — free to download on the iOS App Store with a 7-day free trial of premium features.' },
    ],
  },
  'celiac-app': {
    slug: 'celiac-app',
    title: 'Celiac Disease App | My SafetyZone — Gluten-Free AI Scanner & Recipe AI',
    metaDescription: 'The best celiac disease app on iOS. AI-powered gluten detection in menus and ingredients, allergen-free Recipe AI, QR cards in 200+ languages for safe dining anywhere. Free download.',
    h1: 'The #1 Celiac Disease App',
    h1Accent: 'for safe gluten-free living.',
    keyword: 'celiac disease app',
    audience: 'people with celiac disease, non-celiac gluten sensitivity, and wheat allergies',
    intro: "Celiac disease isn't a preference — it's a medical condition that demands precision. My SafetyZone gives you AI-powered gluten detection, allergen-free Recipe AI, and a QR card that translates your dietary needs into 200+ languages.",
    benefits: [
      { title: 'AI gluten detection', body: 'Detects wheat, barley, rye, malt, brewer\'s yeast, and hidden gluten across menus, ingredient lists, and barcoded products.' },
      { title: 'Recipe AI with gluten-free swaps', body: 'Paste any recipe and get safe, taste-matched gluten-free substitutions that account for binding, texture, and baking ratios.' },
      { title: 'QR celiac card in 200+ languages', body: 'Show one card to communicate celiac disease — and the cross-contact rules that go with it — to staff anywhere in the world.' },
      { title: 'FDA recall alerts', body: 'Get notified instantly when products are recalled for undeclared gluten or wheat.' },
    ],
    faqs: [
      { q: 'Does My SafetyZone account for cross-contact?', a: 'Yes. The QR celiac card communicates not just gluten avoidance but the cross-contact protocols celiac requires — separate prep surfaces, dedicated fryers, and clean utensils.' },
      { q: 'Can I scan ingredient lists for hidden gluten?', a: 'Yes. AI detects wheat, barley, rye, malt, brewer\'s yeast, modified food starch, and ingredient derivatives that other apps miss.' },
      { q: 'Does Recipe AI work for gluten-free baking?', a: 'Yes. Recipe AI understands cooking chemistry — when you swap wheat flour, it adjusts binders, hydration, and ratios so your gluten-free version actually works.' },
      { q: 'Is it free?', a: 'My SafetyZone is free to download on iOS with a 7-day free trial of premium features.' },
    ],
  },
  'epipen-tracker-app': {
    slug: 'epipen-tracker-app',
    title: 'EpiPen Tracker App | My SafetyZone — Expiration Reminders & Auto-Injector Tracking',
    metaDescription: 'The best EpiPen tracker app on iOS. Track every epinephrine auto-injector, get auto-reminders before each expires, and manage inhalers and medical devices in one place. Free download.',
    h1: 'The #1 EpiPen Tracker App',
    h1Accent: 'for life-saving medication.',
    keyword: 'EpiPen tracker app',
    audience: 'anyone carrying epinephrine auto-injectors, parents managing kids\' EpiPens, and caregivers tracking multiple medical devices',
    intro: "Expired EpiPens lose potency. My SafetyZone tracks every epinephrine auto-injector you and your family carry, sends reminders before each one expires, and keeps inhalers and other medical devices on the same schedule.",
    benefits: [
      { title: 'Track every EpiPen', body: 'Add EpiPens for yourself and family members. Each one is monitored independently with its own expiration date.' },
      { title: 'Auto-reminders before expiration', body: 'Get notified weeks in advance so you can refill before your prescription lapses.' },
      { title: 'Inhaler & medical device tracking', body: 'Track albuterol inhalers, AUVI-Q, glucagon, and any other expiring medical device on the same dashboard.' },
      { title: 'Built into a complete allergy app', body: 'Pair EpiPen tracking with QR allergy cards, AI menu scanning, and FDA recall alerts.' },
    ],
    faqs: [
      { q: 'How early do reminders fire?', a: 'Reminders are sent weeks before expiration so you have time to refill your prescription before your current EpiPen lapses.' },
      { q: 'Can I track EpiPens for my whole family?', a: 'Yes. Add an EpiPen for each family member with its own expiration date and individual reminders.' },
      { q: 'Does it track other auto-injectors?', a: 'Yes — EpiPen, AUVI-Q, generic epinephrine auto-injectors, and any other medical device with an expiration date.' },
      { q: 'Is it free?', a: 'My SafetyZone is free to download on iOS. EpiPen tracking is included.' },
    ],
  },
  'qr-allergy-card': {
    slug: 'qr-allergy-card',
    title: 'QR Allergy Card App | My SafetyZone — Translated into 200+ Languages',
    metaDescription: 'The best QR allergy card app. Generate a personal QR code that communicates your food allergies in 200+ languages — perfect for restaurants, travel, and dining out. Free on iOS.',
    h1: 'QR Allergy Cards',
    h1Accent: 'in 200+ languages.',
    keyword: 'QR allergy card',
    audience: 'people who travel internationally, eat out frequently, or need to communicate complex allergies to non-English-speaking staff',
    intro: "Saying \"I have a peanut allergy\" in Japanese, Thai, or Italian shouldn't be a barrier to eating safely. My SafetyZone generates a QR code that contains your full allergy profile, instantly translated into the local language at any restaurant — anywhere in the world.",
    benefits: [
      { title: '200+ languages, auto-translated', body: 'When staff scans your QR card, it appears in their language. No app required on their end — just a phone camera.' },
      { title: 'Cross-contact instructions included', body: 'Communicate not just allergens but the protocols you need — clean prep surfaces, dedicated fryers, no shared utensils.' },
      { title: 'Travel-ready', body: 'Pair with Travel Allergen guides for destination-specific safety tips and local allergen databases.' },
      { title: 'Always up to date', body: 'Update your allergy profile in the app; the QR card auto-updates. No reprinting cards.' },
    ],
    faqs: [
      { q: 'Do restaurants need a special app to scan it?', a: 'No. Any phone camera or QR reader scans the card and opens a translated allergy summary in their browser.' },
      { q: 'Which languages are supported?', a: 'My SafetyZone supports 200+ languages, including Spanish, French, German, Italian, Japanese, Mandarin, Korean, Arabic, Hindi, Portuguese, Thai, Vietnamese, and many more.' },
      { q: 'Can I print it as a physical card?', a: 'Yes. You can print or save your QR card to your phone\'s wallet for quick access without unlocking the app.' },
      { q: 'Is it free?', a: 'Yes — QR Allergy Cards are included free with My SafetyZone on iOS.' },
    ],
  },
  'gluten-free-app': {
    slug: 'gluten-free-app',
    title: 'Gluten Free App | My SafetyZone — AI Gluten Scanner & Safe Recipe Finder',
    metaDescription: 'The #1 gluten free app on iOS. AI-powered gluten detection, allergen-free Recipe AI, QR cards in 200+ languages, and FDA recall alerts. Built for celiac and gluten sensitivity. Free download.',
    h1: 'The #1 Gluten Free App',
    h1Accent: 'for safe eating.',
    keyword: 'gluten free app',
    audience: 'anyone living gluten-free — celiac, gluten-sensitive, or by choice',
    intro: "Whether you're celiac, gluten-sensitive, or gluten-free by choice, My SafetyZone makes safe eating effortless. AI detects gluten in menus and ingredients, Recipe AI swaps in safe substitutions, and your QR card communicates your needs in 200+ languages.",
    benefits: [
      { title: 'AI gluten scanning', body: 'Detect wheat, barley, rye, malt, and hidden gluten in menus, recipes, and ingredient lists.' },
      { title: 'Gluten-free Recipe AI', body: 'Paste any recipe and get safe, tasty gluten-free substitutions that respect baking chemistry.' },
      { title: 'Travel allergen guides', body: 'Destination-specific gluten safety guides for international and domestic travel.' },
      { title: 'FDA recall alerts', body: 'Real-time notifications when products are recalled for undeclared gluten.' },
    ],
    faqs: [
      { q: 'Is it built for celiac disease?', a: 'Yes — My SafetyZone takes celiac seriously, including cross-contact protocols and the precision celiac requires.' },
      { q: 'Can I scan packaged food barcodes?', a: 'Barcode allergen scanning is rolling out. AI ingredient analysis, menu scanning, and Recipe AI are live today.' },
      { q: 'Does it work for non-celiac gluten sensitivity?', a: 'Yes. Customize your profile to flag gluten, wheat, or both — whichever applies to you.' },
      { q: 'Is it free?', a: 'Free to download on iOS with a 7-day free trial of premium features.' },
    ],
  },
  'food-allergy-app-for-kids': {
    slug: 'food-allergy-app-for-kids',
    title: 'Food Allergy App for Kids | My SafetyZone — School-Ready QR Cards & EpiPen Reminders',
    metaDescription: 'The best food allergy app for kids and parents. Allergy profiles for each child, school-ready QR cards in 200+ languages, EpiPen expiration reminders, and FDA recall alerts. Free on iOS.',
    h1: 'Food Allergy App',
    h1Accent: 'built for kids and parents.',
    keyword: 'food allergy app for kids',
    audience: 'parents managing food allergies for one or more children, caregivers, and grandparents',
    intro: "Managing a child's food allergy is a full-time job. My SafetyZone gives parents one place to track every allergy, every EpiPen, and every meal — plus QR cards that schools, daycares, and restaurants can scan instantly.",
    benefits: [
      { title: 'Profile per child', body: 'Each child gets their own allergy profile, QR card, and EpiPen tracker.' },
      { title: 'School & daycare ready', body: 'Print or share QR cards with teachers, nurses, and caregivers — translated into the school\'s language.' },
      { title: 'EpiPen reminders', body: 'Never get caught with an expired auto-injector. Reminders fire weeks before each one expires.' },
      { title: 'FDA recall alerts', body: 'Real-time notifications protect your family from recalled products with undeclared allergens.' },
    ],
    faqs: [
      { q: 'Can I manage multiple kids?', a: 'Yes. Add a profile for each child with their own allergens, EpiPens, and QR card.' },
      { q: 'Is it safe for the child to use?', a: 'Most parents manage the app themselves and share QR cards with the child or their caregivers. The app uses encrypted health data storage.' },
      { q: 'How does it help with school?', a: 'Generate a QR card the school nurse, teachers, and cafeteria staff can scan. It includes allergens, severity, EpiPen location, and emergency contacts.' },
      { q: 'Is it free?', a: 'Yes — free on iOS with a 7-day free trial of premium features.' },
    ],
  },
  'spokin-alternative': {
    slug: 'spokin-alternative',
    title: 'Best Spokin Alternative 2026 | My SafetyZone Food Allergy App',
    metaDescription: 'Looking for a Spokin alternative? My SafetyZone adds AI allergen scanning, QR allergy cards in 200+ languages, EpiPen tracking, and FDA recall alerts — free on iOS.',
    h1: 'The best Spokin alternative',
    h1Accent: 'in 2026.',
    keyword: 'spokin alternative',
    audience: 'Spokin users, food allergy app shoppers, and travelers comparing allergy management apps',
    intro: "Spokin built a great restaurant community. My SafetyZone goes further — adding AI allergen scanning of menus, recipes, and ingredients, QR allergy cards translated into 200+ languages, EpiPen and inhaler expiration tracking, and live FDA recall alerts. All free on iOS.",
    benefits: [
      { title: 'AI scanning Spokin doesn\'t have', body: 'Snap a menu, recipe, or ingredient list and AI flags every allergen — including hidden derivatives. Spokin relies on community reviews; My SafetyZone reads the actual food.' },
      { title: 'QR cards in 200+ languages', body: 'Travel anywhere and hand any restaurant a QR card that explains your allergies in their language. Spokin focuses on US restaurant reviews.' },
      { title: 'EpiPen + medical device tracker', body: 'Auto-reminders before every EpiPen, inhaler, and medical device expires. Built into the same app.' },
      { title: 'Real-time FDA recall alerts', body: 'Get push notifications the moment a product is recalled for undeclared allergens.' },
    ],
    faqs: [
      { q: 'How is My SafetyZone different from Spokin?', a: 'Spokin is a community-based restaurant review app focused on US dining. My SafetyZone adds AI-powered allergen scanning, multilingual QR translation cards, EpiPen and medical device expiration tracking, and live FDA recall alerts — features Spokin does not provide.' },
      { q: 'Is My SafetyZone free like Spokin?', a: 'Yes. My SafetyZone is free to download on the iOS App Store with a 7-day free trial of premium AI features.' },
      { q: 'Does My SafetyZone work outside the US?', a: 'Yes — that\'s a core advantage. The QR allergy card translates into 200+ languages, making it ideal for international travel where Spokin\'s US-focused restaurant reviews are limited.' },
      { q: 'Can I migrate my allergy profile from Spokin?', a: 'You\'ll set up a fresh profile in My SafetyZone — it takes about a minute. The app then powers QR cards, AI scans, and recall alerts customized to your allergens.' },
    ],
  },
  'fig-alternative': {
    slug: 'fig-alternative',
    title: 'Best Fig App Alternative 2026 | My SafetyZone Allergen Scanner',
    metaDescription: 'Looking for a Fig (foodisgood) alternative? My SafetyZone scans menus, recipes, and ingredients with AI, plus QR allergy cards, EpiPen tracking, and FDA recall alerts. Free on iOS.',
    h1: 'The best Fig alternative',
    h1Accent: 'for food allergies.',
    keyword: 'fig app alternative',
    audience: 'Fig (foodisgood) users, grocery scanner shoppers, and people with multiple dietary restrictions',
    intro: "Fig is great for grocery scanning by diet. My SafetyZone covers grocery, restaurants, recipes, and travel translation in one free iOS app — plus EpiPen tracking and FDA recall alerts that Fig doesn\u2019t offer.",
    benefits: [
      { title: 'Beyond grocery scanning', body: 'Fig focuses on packaged grocery products. My SafetyZone scans menus, recipes, and ingredient lists too — wherever you eat.' },
      { title: 'QR allergy cards in 200+ languages', body: 'Show one card at any restaurant in any country. Fig doesn\'t cover dining out or travel.' },
      { title: 'EpiPen, inhaler, and medical device tracking', body: 'Auto-reminders before each device expires. A complete safety net Fig doesn\'t include.' },
      { title: 'FDA recall alerts in real time', body: 'Push notifications when a product is recalled for undeclared allergens — for every diet you track.' },
    ],
    faqs: [
      { q: 'How does My SafetyZone compare to Fig?', a: 'Fig specializes in grocery product filtering by diet. My SafetyZone covers grocery + menus + recipes + travel cards + EpiPen tracking + FDA recalls in a single free app, built specifically for people with food allergies and dietary restrictions.' },
      { q: 'Is My SafetyZone free?', a: 'Yes. Free download on the iOS App Store with a 7-day premium trial. Core allergen scanning and QR cards stay free forever.' },
      { q: 'Does My SafetyZone support multiple diets like Fig?', a: 'Yes — peanuts, tree nuts, dairy, eggs, wheat, gluten, soy, fish, shellfish, sesame, plus 50+ sensitivities and dietary preferences (halal, kosher, vegan, vegetarian, paleo, keto, custom).' },
      { q: 'Why pick My SafetyZone over Fig?', a: 'If you only shop groceries, Fig works. If you eat out, travel, manage EpiPens, or want recall alerts, My SafetyZone is more complete — and still free.' },
    ],
  },
  'allergyeats-alternative': {
    slug: 'allergyeats-alternative',
    title: 'Best AllergyEats Alternative 2026 | My SafetyZone Food Allergy App',
    metaDescription: 'AllergyEats alternative with AI menu scanning, QR allergy cards in 200+ languages, EpiPen tracker, and FDA recall alerts. Free on iOS.',
    h1: 'The best AllergyEats alternative',
    h1Accent: 'for safer dining.',
    keyword: 'allergyeats alternative',
    audience: 'AllergyEats users, restaurant-allergy diners, and food-allergic travelers',
    intro: "AllergyEats helped pioneer allergy-friendly restaurant reviews. My SafetyZone adds the missing layer — AI that reads the actual menu, multilingual QR cards for any restaurant on earth, and EpiPen + recall safety in one free iOS app.",
    benefits: [
      { title: 'AI reads the menu, not just reviews', body: 'AllergyEats relies on user reviews. My SafetyZone\'s AI scans the menu itself and flags allergens and hidden derivatives in seconds.' },
      { title: 'Works at every restaurant, not just listed ones', body: 'No more "no reviews for this restaurant." Scan any menu, anywhere.' },
      { title: 'Travel-ready QR allergy cards', body: '200+ languages for international dining. AllergyEats is US-focused.' },
      { title: 'EpiPen + recall alerts built in', body: 'Track every auto-injector and get push alerts on FDA recalls.' },
    ],
    faqs: [
      { q: 'Why switch from AllergyEats?', a: 'AllergyEats is a directory of allergy-friendly restaurants. My SafetyZone works at every restaurant — its AI reads the menu directly and translates your allergies into 200+ languages so you\'re covered anywhere, even abroad.' },
      { q: 'Is the AI accurate for hidden allergens?', a: 'My SafetyZone\'s AI is trained on FDA allergen databases and ingredient derivative lists, so it catches hidden sources (arachis oil, casein, whey, gluten in modified starch, etc.) that user reviews often miss.' },
      { q: 'Is it free?', a: 'Yes — free on iOS with a 7-day free trial of premium AI features.' },
      { q: 'Does it replace AllergyEats?', a: 'For most users, yes. You get menu-level AI, multilingual cards, EpiPen tracking, and recalls all in one app.' },
    ],
  },
  'find-me-gluten-free-alternative': {
    slug: 'find-me-gluten-free-alternative',
    title: 'Best Find Me Gluten Free Alternative | My SafetyZone Celiac App',
    metaDescription: 'Find Me Gluten Free alternative with AI gluten detection, allergen-free Recipe AI, QR celiac cards in 200+ languages, and FDA recall alerts. Free on iOS.',
    h1: 'The best Find Me Gluten Free alternative',
    h1Accent: 'for celiacs.',
    keyword: 'find me gluten free alternative',
    audience: 'Find Me Gluten Free users, celiac travelers, and gluten-sensitive diners',
    intro: "Find Me Gluten Free helps you find restaurants. My SafetyZone goes further — AI that detects gluten in every menu and ingredient list, Recipe AI with smart gluten-free swaps, and a multilingual QR celiac card that explains cross-contact rules in any language.",
    benefits: [
      { title: 'AI gluten detection on any menu', body: 'Detects wheat, barley, rye, malt, brewer\'s yeast, modified starches, and hidden derivatives Find Me Gluten Free reviews can\'t catch.' },
      { title: 'Recipe AI built for gluten-free baking', body: 'Paste any recipe and get taste-matched gluten-free swaps that respect binding, hydration, and ratios.' },
      { title: 'QR celiac card in 200+ languages', body: 'Communicates celiac disease AND cross-contact protocols (separate fryers, clean prep) anywhere on earth.' },
      { title: 'FDA recall alerts for undeclared gluten', body: 'Real-time push notifications the moment products are recalled.' },
    ],
    faqs: [
      { q: 'How is My SafetyZone different from Find Me Gluten Free?', a: 'Find Me Gluten Free is a restaurant directory with user reviews. My SafetyZone adds AI that scans menus and ingredients for gluten, Recipe AI for safe baking swaps, multilingual QR celiac cards for travel, and live FDA recall alerts.' },
      { q: 'Does it handle cross-contact?', a: 'Yes — the QR celiac card explicitly communicates cross-contact requirements (separate prep surfaces, dedicated fryers, clean utensils) in 200+ languages.' },
      { q: 'Is it free?', a: 'Yes. Free on iOS with a 7-day premium trial.' },
      { q: 'Can I use it abroad?', a: 'That\'s where the QR celiac card shines — 200+ languages including Italian, Spanish, French, Mandarin, Japanese, Arabic, and more.' },
    ],
  },
  'picknic-alternative': {
    slug: 'picknic-alternative',
    title: 'Best Picknic Alternative 2026 | My SafetyZone AI Allergen Scanner',
    metaDescription: 'Picknic alternative with broader AI allergen scanning, QR cards in 200+ languages, EpiPen tracking, FDA recall alerts, and Recipe AI. Free on iOS.',
    h1: 'The best Picknic alternative',
    h1Accent: 'for food allergies.',
    keyword: 'picknic alternative',
    audience: 'Picknic users, allergen scanner shoppers, and people with multiple food allergies',
    intro: "Picknic helps filter foods by diet. My SafetyZone adds AI menu scanning, multilingual QR allergy cards, EpiPen tracking, FDA recall alerts, and Recipe AI — a complete safety platform in one free iOS app.",
    benefits: [
      { title: 'Broader AI allergen detection', body: '50+ allergens and dietary preferences with derivative-level detection across menus, recipes, and ingredient lists.' },
      { title: 'Multilingual QR allergy cards', body: '200+ languages for travel and international dining.' },
      { title: 'EpiPen + medical device tracker', body: 'Never carry an expired auto-injector again.' },
      { title: 'Recipe AI + FDA recall alerts', body: 'Smart allergen-free recipe swaps and real-time recall push notifications.' },
    ],
    faqs: [
      { q: 'Why pick My SafetyZone over Picknic?', a: 'My SafetyZone bundles AI menu scanning, multilingual QR cards, EpiPen tracking, FDA recalls, and Recipe AI in one free app — broader coverage than Picknic\'s diet-filter focus.' },
      { q: 'Is it free?', a: 'Yes — free on iOS with a 7-day free trial of premium AI features.' },
      { q: 'Which allergens does it detect?', a: 'The Big 9 (peanuts, tree nuts, milk, eggs, wheat, soy, fish, shellfish, sesame), plus 50+ additional sensitivities and lifestyle diets (halal, kosher, vegan, keto, paleo, custom).' },
      { q: 'Does it work for kids?', a: 'Yes. Build a profile per child with their allergens, EpiPens, and a school-ready QR card.' },
    ],
  },
};

export const landingSlugs = Object.keys(landingConfigs);
