import type { LandingConfig } from './_template';

export const landingConfigs: Record<string, LandingConfig> = {
  'peanut-allergy-app': {
    slug: 'peanut-allergy-app',
    title: 'Peanut Allergy App | My SafetyZone — AI Scanner',
    metaDescription: 'Peanut allergy app for iOS. AI detects peanuts in menus and recipes, QR cards in 150 languages, EpiPen tracker, FDA alerts. Free.',
    h1: 'The Peanut Allergy App',
    h1Accent: 'for iOS.',
    keyword: 'peanut allergy app',
    audience: 'people with peanut allergies, parents of kids with peanut allergies, and adults managing anaphylactic peanut allergies',
    intro: "Living with a peanut allergy means every meal is a calculation. My SafetyZone takes the guesswork out — AI-powered peanut detection across menus, recipes, and ingredient lists, plus a QR allergy card you can show any restaurant, anywhere in the world.",
    benefits: [
      { title: 'AI peanut detection', body: 'Scan menus, recipes, and ingredients with AI that flags peanuts, peanut oil, peanut flour, and hidden derivatives like arachis oil.' },
      { title: 'QR allergy card in 150 languages', body: 'One scan and any restaurant — domestic or international — knows you have a peanut allergy in their native language.' },
      { title: 'EpiPen expiration tracker', body: 'Never carry an expired epinephrine auto-injector again. Auto-reminders before each EpiPen expires.' },
      { title: 'FDA recall alerts', body: 'Real-time notifications when products are recalled for undeclared peanut content.' },
    ],
    faqs: [
      { q: 'How does My SafetyZone detect peanuts?', a: 'My SafetyZone uses AI trained on FDA allergen databases and ingredient derivative lists to flag peanuts, peanut protein, peanut oil, peanut flour, arachis oil, mandelonas, and other hidden peanut sources in menus, recipes, and packaged foods.' },
      { q: 'Is My SafetyZone good for kids with peanut allergies?', a: 'Yes. Parents can build allergy profiles for each child, generate QR allergy cards for school and daycare staff, and track every EpiPen expiration date in one place.' },
      { q: 'Does it work for tree nut allergies too?', a: 'Yes. My SafetyZone supports peanuts and all tree nuts (almonds, cashews, walnuts, pecans, pistachios, macadamia, Brazil nuts, hazelnuts), plus 50+ other allergens and dietary needs.' },
      { q: 'Is My SafetyZone free?', a: 'Yes — free to download on the iOS App Store with a 7-day free trial of premium features.' },
    ],
  },
  'celiac-app': {
    slug: 'celiac-app',
    title: 'Celiac App | My SafetyZone — Gluten-Free AI',
    metaDescription: 'Best celiac app for iOS. AI gluten detection, allergen-free Recipe AI, QR cards in 150 languages, FDA alerts. Free download.',
    h1: 'The Celiac Disease App',
    h1Accent: 'for safe gluten-free living.',
    keyword: 'celiac disease app',
    audience: 'people with celiac disease, non-celiac gluten sensitivity, and wheat allergies',
    intro: "Celiac disease isn't a preference — it's a medical condition that demands precision. My SafetyZone gives you AI-powered gluten detection, allergen-free Recipe AI, and a QR card that translates your dietary needs into 150 languages.",
    benefits: [
      { title: 'AI gluten detection', body: 'Detects wheat, barley, rye, malt, brewer\'s yeast, and hidden gluten across menus, ingredient lists, and barcoded products.' },
      { title: 'Recipe AI with gluten-free swaps', body: 'Paste any recipe and get safe, taste-matched gluten-free substitutions that account for binding, texture, and baking ratios.' },
      { title: 'QR celiac card in 150 languages', body: 'Show one card to communicate celiac disease — and the cross-contact rules that go with it — to staff anywhere in the world.' },
      { title: 'FDA recall alerts', body: 'Get notified instantly when products are recalled for undeclared gluten or wheat.' },
    ],
    faqs: [
      { q: 'Does My SafetyZone account for cross-contact?', a: 'Yes. The QR celiac card communicates not just gluten avoidance but the cross-contact protocols celiac requires — separate prep surfaces, dedicated fryers, and clean utensils.' },
      { q: 'Can I scan ingredient lists for hidden gluten?', a: 'Yes. AI detects wheat, barley, rye, malt, brewer\'s yeast, modified food starch, and ingredient derivatives that other apps miss.' },
      { q: 'Does Recipe AI work for gluten-free baking?', a: 'Yes. Recipe AI understands cooking chemistry — when you swap wheat flour, it adjusts binders, hydration, and ratios so your gluten-free version actually works.' },
      { q: 'Is it free?', a: 'My SafetyZone is free to download on iOS with a 7-day free trial of premium features.' },
    ],
  },
  'epipen-tracker-app': {
    slug: 'epipen-tracker-app',
    title: 'EpiPen Tracker App | My SafetyZone — Reminders',
    metaDescription: 'Best EpiPen tracker for iOS. Track auto-injectors, get expiration reminders, manage inhalers and devices. Free download.',
    h1: 'The EpiPen Tracker App',
    h1Accent: 'for life-saving medication.',
    keyword: 'EpiPen tracker app',
    audience: 'anyone carrying epinephrine auto-injectors, parents managing kids\' EpiPens, and caregivers tracking multiple medical devices',
    intro: "Expired EpiPens lose potency. My SafetyZone tracks every epinephrine auto-injector you and your family carry, sends reminders before each one expires, and keeps inhalers and other medical devices on the same schedule.",
    benefits: [
      { title: 'Track every EpiPen', body: 'Add EpiPens for yourself and family members. Each one is monitored independently with its own expiration date.' },
      { title: 'Auto-reminders before expiration', body: 'Get notified weeks in advance so you can refill before your prescription lapses.' },
      { title: 'Inhaler & medical device tracking', body: 'Track albuterol inhalers, AUVI-Q, glucagon, and any other expiring medical device on the same dashboard.' },
      { title: 'Built into a complete allergy app', body: 'Pair EpiPen tracking with QR allergy cards, AI menu scanning, and FDA recall alerts.' },
    ],
    faqs: [
      { q: 'How early do reminders fire?', a: 'Reminders are sent weeks before expiration so you have time to refill your prescription before your current EpiPen lapses.' },
      { q: 'Can I track EpiPens for my whole family?', a: 'Yes. Add an EpiPen for each family member with its own expiration date and individual reminders.' },
      { q: 'Does it track other auto-injectors?', a: 'Yes — EpiPen, AUVI-Q, generic epinephrine auto-injectors, and any other medical device with an expiration date.' },
      { q: 'Is it free?', a: 'My SafetyZone is free to download on iOS. EpiPen tracking is included.' },
    ],
  },
  'qr-allergy-card': {
    slug: 'qr-allergy-card',
    title: 'QR Allergy Card | My SafetyZone — 150 Languages',
    metaDescription: 'Best QR allergy card app. Generate a personal QR code communicating your allergies in 150 languages. Perfect for travel. Free on iOS.',
    h1: 'QR Allergy Cards',
    h1Accent: 'in 150 languages.',
    keyword: 'QR allergy card',
    audience: 'people who travel internationally, eat out frequently, or need to communicate complex allergies to non-English-speaking staff',
    intro: "Saying \"I have a peanut allergy\" in Japanese, Thai, or Italian shouldn't be a barrier to eating safely. My SafetyZone generates a QR code that contains your full allergy profile, instantly translated into the local language at any restaurant — anywhere in the world.",
    benefits: [
      { title: '150 languages, auto-translated', body: 'When staff scans your QR card, it appears in their language. No app required on their end — just a phone camera.' },
      { title: 'Cross-contact instructions included', body: 'Communicate not just allergens but the protocols you need — clean prep surfaces, dedicated fryers, no shared utensils.' },
      { title: 'Travel-ready', body: 'Pair with Travel Allergen guides for destination-specific safety tips and local allergen databases.' },
      { title: 'Always up to date', body: 'Update your allergy profile in the app; the QR card auto-updates. No reprinting cards.' },
    ],
    faqs: [
      { q: 'Do restaurants need a special app to scan it?', a: 'No. Any phone camera or QR reader scans the card and opens a translated allergy summary in their browser.' },
      { q: 'Which languages are supported?', a: 'My SafetyZone supports 150 languages, including Spanish, French, German, Italian, Japanese, Mandarin, Korean, Arabic, Hindi, Portuguese, Thai, Vietnamese, and many more.' },
      { q: 'Can I print it as a physical card?', a: 'Yes. You can print or save your QR card to your phone\'s wallet for quick access without unlocking the app.' },
      { q: 'Is it free?', a: 'Yes — QR Allergy Cards are included free with My SafetyZone on iOS.' },
    ],
  },
  'gluten-free-app': {
    slug: 'gluten-free-app',
    title: 'Gluten Free App | My SafetyZone — AI Scanner',
    metaDescription: 'Gluten free app for iOS. AI gluten detection, allergen-free Recipe AI, QR cards, FDA alerts. Built for celiac. Free.',
    h1: 'The Gluten Free App',
    h1Accent: 'for safe eating.',
    keyword: 'gluten free app',
    audience: 'anyone living gluten-free — celiac, gluten-sensitive, or by choice',
    intro: "Whether you're celiac, gluten-sensitive, or gluten-free by choice, My SafetyZone makes safe eating effortless. AI detects gluten in menus and ingredients, Recipe AI swaps in safe substitutions, and your QR card communicates your needs in 150 languages.",
    benefits: [
      { title: 'AI gluten scanning', body: 'Detect wheat, barley, rye, malt, and hidden gluten in menus, recipes, and ingredient lists.' },
      { title: 'Gluten-free Recipe AI', body: 'Paste any recipe and get safe, tasty gluten-free substitutions that respect baking chemistry.' },
      { title: 'Travel allergen guides', body: 'Destination-specific gluten safety guides for international and domestic travel.' },
      { title: 'FDA recall alerts', body: 'Real-time notifications when products are recalled for undeclared gluten.' },
    ],
    faqs: [
      { q: 'Is it built for celiac disease?', a: 'Yes — My SafetyZone takes celiac seriously, including cross-contact protocols and the precision celiac requires.' },
      { q: 'Can I scan packaged food barcodes?', a: 'Barcode allergen scanning is rolling out. AI ingredient analysis, menu scanning, and Recipe AI are live today.' },
      { q: 'Does it work for non-celiac gluten sensitivity?', a: 'Yes. Customize your profile to flag gluten, wheat, or both — whichever applies to you.' },
      { q: 'Is it free?', a: 'Free to download on iOS with a 7-day free trial of premium features.' },
    ],
  },
  'food-allergy-app-for-kids': {
    slug: 'food-allergy-app-for-kids',
    title: 'Food Allergy App for Kids | My SafetyZone',
    metaDescription: 'Best food allergy app for kids. Allergy profiles, school-ready QR cards in 150 languages, EpiPen reminders, FDA alerts. Free.',
    h1: 'Food Allergy App',
    h1Accent: 'built for kids and parents.',
    keyword: 'food allergy app for kids',
    audience: 'parents managing food allergies for one or more children, caregivers, and grandparents',
    intro: "Managing a child's food allergy is a full-time job. My SafetyZone gives parents one place to track every allergy, every EpiPen, and every meal — plus QR cards that schools, daycares, and restaurants can scan instantly.",
    benefits: [
      { title: 'Profile per child', body: 'Each child gets their own allergy profile, QR card, and EpiPen tracker.' },
      { title: 'School & daycare ready', body: 'Print or share QR cards with teachers, nurses, and caregivers — translated into the school\'s language.' },
      { title: 'EpiPen reminders', body: 'Never get caught with an expired auto-injector. Reminders fire weeks before each one expires.' },
      { title: 'FDA recall alerts', body: 'Real-time notifications protect your family from recalled products with undeclared allergens.' },
    ],
    faqs: [
      { q: 'Can I manage multiple kids?', a: 'Yes. Add a profile for each child with their own allergens, EpiPens, and QR card.' },
      { q: 'Is it safe for the child to use?', a: 'Most parents manage the app themselves and share QR cards with the child or their caregivers. The app uses encrypted health data storage.' },
      { q: 'How does it help with school?', a: 'Generate a QR card the school nurse, teachers, and cafeteria staff can scan. It includes allergens, severity, EpiPen location, and emergency contacts.' },
      { q: 'Is it free?', a: 'Yes — free on iOS with a 7-day free trial of premium features.' },
    ],
  },
  'dairy-allergy-app': {
    slug: 'dairy-allergy-app', title: 'Dairy Allergy App | My SafetyZone', metaDescription: 'Manage a milk or dairy allergy with translated QR allergy cards, recipe substitutions, medication reminders, and FDA recall alerts on iOS.', h1: 'The Dairy Allergy App', h1Accent: 'for clearer everyday choices.', keyword: 'dairy allergy app', audience: 'people with milk and dairy allergies and families managing dairy avoidance', intro: 'Dairy can appear under many ingredient names. My SafetyZone keeps your allergy card, recipe substitutions, travel guidance, medication reminders, and recall information together.',
    benefits: [{ title: 'Clear dairy allergy card', body: 'Share your dairy allergy and dietary needs through a personal QR card.' }, { title: 'Recipe substitutions', body: 'Explore dairy-free ingredient ideas shaped around the recipe you want to make.' }, { title: 'Travel communication', body: 'Communicate your needs across language barriers while dining away from home.' }, { title: 'Recall information', body: 'Keep FDA food recall information alongside your everyday allergy tools.' }],
    faqs: [{ q: 'Does My SafetyZone replace checking ingredients?', a: 'No. Always verify labels and preparation with staff. The app supports clearer decisions but cannot guarantee a food is allergen-free.' }, { q: 'Can I use the allergy card abroad?', a: 'Yes. The QR allergy card is designed to communicate dietary needs across supported languages.' }, { q: 'Does it include recipe help?', a: 'Recipe AI can suggest ingredient substitutions, but users should independently verify every ingredient.' }, { q: 'Where is it available?', a: 'My SafetyZone is available for iOS.' }],
  },
  'egg-allergy-app': {
    slug: 'egg-allergy-app', title: 'Egg Allergy App | My SafetyZone', metaDescription: 'An iOS companion for egg allergies with QR allergy cards, travel communication, recipe substitutions, medication reminders, and recall information.', h1: 'The Egg Allergy App', h1Accent: 'for meals, recipes, and travel.', keyword: 'egg allergy app', audience: 'people with egg allergies and parents managing an egg allergy', intro: 'From baked goods to sauces, egg can be difficult to navigate. My SafetyZone helps you communicate your needs and organize practical allergy tools.',
    benefits: [{ title: 'Personal QR allergy card', body: 'Keep egg allergy information ready to share at restaurants, schools, and events.' }, { title: 'Recipe inspiration', body: 'Explore possible egg substitutions and recipe ideas in one place.' }, { title: 'Medication reminders', body: 'Track expiration dates for EpiPens, inhalers, and other medical devices.' }, { title: 'Travel guidance', body: 'Prepare for dining conversations when you are away from home.' }],
    faqs: [{ q: 'Can the app confirm food is egg-free?', a: 'No. Always confirm ingredients and cross-contact procedures directly with staff.' }, { q: 'Can parents use it for a child?', a: 'Parents can keep allergy communication and medication tools together for daily routines.' }, { q: 'Are substitution suggestions guaranteed safe?', a: 'No. Suggestions are informational and every ingredient should be independently verified.' }, { q: 'Is Android available?', a: 'The app is currently available on iOS, with Android planned.' }],
  },
  'tree-nut-allergy-app': {
    slug: 'tree-nut-allergy-app', title: 'Tree Nut Allergy App | My SafetyZone', metaDescription: 'Manage tree nut allergies with translated QR cards, travel tools, medication reminders, recipe support, and FDA recall information.', h1: 'The Tree Nut Allergy App', h1Accent: 'for life beyond the label.', keyword: 'tree nut allergy app', audience: 'people managing almond, cashew, walnut, pistachio, pecan, hazelnut, and other tree nut allergies', intro: 'Tree nut allergies can involve several distinct ingredients and cross-contact concerns. My SafetyZone helps keep your communication and planning tools organized.',
    benefits: [{ title: 'Detailed allergy profile', body: 'Record the tree nuts that matter to you and keep them in a shareable allergy card.' }, { title: 'Dining communication', body: 'Start a clearer conversation with restaurant staff at home and while traveling.' }, { title: 'Medication tracking', body: 'Keep expiration reminders for essential medications and devices.' }, { title: 'Recall awareness', body: 'Review FDA food recall information from within your allergy toolkit.' }],
    faqs: [{ q: 'Can I list individual tree nuts?', a: 'Your profile can reflect the dietary needs and allergens relevant to you.' }, { q: 'Does it detect cross-contact?', a: 'No. The app cannot see kitchen practices. Always ask staff about preparation and shared equipment.' }, { q: 'Can I share my profile?', a: 'The QR allergy card is made for quick, clear sharing.' }, { q: 'Is the app medical advice?', a: 'No. My SafetyZone provides informational tools and does not replace professional medical advice.' }],
  },
  'sesame-allergy-app': {
    slug: 'sesame-allergy-app', title: 'Sesame Allergy App | My SafetyZone', metaDescription: 'Organize sesame allergy communication, translated QR cards, travel planning, medication reminders, and food recall information on iOS.', h1: 'The Sesame Allergy App', h1Accent: 'for clearer communication.', keyword: 'sesame allergy app', audience: 'people with sesame allergies and families managing sesame avoidance', intro: 'Sesame can appear in breads, sauces, seasoning blends, and international cuisines. My SafetyZone helps you prepare, communicate, and keep essential tools close.',
    benefits: [{ title: 'QR allergy communication', body: 'Share sesame allergy information through a personal card.' }, { title: 'Travel-ready tools', body: 'Prepare for allergy conversations across supported languages.' }, { title: 'Medication organization', body: 'Track EpiPen, inhaler, and medical device expiration dates.' }, { title: 'Recall information', body: 'See FDA recall information alongside the rest of your allergy toolkit.' }],
    faqs: [{ q: 'Does it identify every sesame ingredient?', a: 'No tool can guarantee identification. Always verify the complete ingredient list and preparation process.' }, { q: 'Can restaurants scan the card?', a: 'The QR card is designed to make your profile easy to share using a phone.' }, { q: 'Can I use it internationally?', a: 'Travel and translation tools are designed to support communication abroad.' }, { q: 'Is it free?', a: 'My SafetyZone is free to download on iOS; check the App Store for current premium terms.' }],
  },
  'allergy-card-for-restaurants': {
    slug: 'allergy-card-for-restaurants', title: 'Allergy Card for Restaurants | My SafetyZone', metaDescription: 'Create a QR allergy card for restaurants and communicate dietary needs across supported languages with My SafetyZone for iOS.', h1: 'An Allergy Card', h1Accent: 'made for restaurant conversations.', keyword: 'allergy card for restaurants', audience: 'diners who need to communicate food allergies and dietary restrictions at restaurants', intro: 'A clear allergy conversation starts before the meal arrives. Build a personal QR card that helps restaurant staff understand your dietary needs.',
    benefits: [{ title: 'One personal profile', body: 'Keep your relevant allergies and dietary needs together.' }, { title: 'Simple QR sharing', body: 'Open and share your card during a restaurant conversation.' }, { title: 'Language support', body: 'Communicate across supported languages while dining and traveling.' }, { title: 'Always confirm with staff', body: 'Use the card to begin a conversation about ingredients, preparation, and cross-contact.' }],
    faqs: [{ q: 'Does a QR card guarantee a safe meal?', a: 'No. It supports communication, but only the restaurant can explain its ingredients and kitchen practices.' }, { q: 'Does staff need the app?', a: 'The card is designed to be shared through a QR code.' }, { q: 'Can I update my needs?', a: 'You can keep your personal allergy information current in the app.' }, { q: 'Should I still speak to a manager?', a: 'Yes. Always confirm ingredients and cross-contact procedures directly with qualified restaurant staff.' }],
  },
  'food-allergy-travel-app': {
    slug: 'food-allergy-travel-app', title: 'Food Allergy Travel App | My SafetyZone', metaDescription: 'Travel with food allergies using QR allergy cards, language support, destination guidance, and medication reminders in My SafetyZone for iOS.', h1: 'Food Allergy Travel', h1Accent: 'with a little more confidence.', keyword: 'food allergy travel app', audience: 'travelers managing food allergies, celiac disease, or dietary restrictions away from home', intro: 'New destinations bring new ingredients, languages, and dining routines. My SafetyZone keeps communication, planning, and medication tools close throughout the trip.',
    benefits: [{ title: 'Translated allergy card', body: 'Share your dietary needs across supported languages.' }, { title: 'Destination guidance', body: 'Review practical allergen information while planning a trip.' }, { title: 'Medication reminders', body: 'Check expiration dates before departure and keep essential devices organized.' }, { title: 'One travel companion', body: 'Keep allergy communication, recipes, recalls, and planning tools together.' }],
    faqs: [{ q: 'Can I use the card without restaurant staff installing the app?', a: 'The QR card is designed for simple browser-based sharing.' }, { q: 'Does the app guarantee safe travel dining?', a: 'No. Always verify ingredients and preparation with staff and follow your clinician’s travel guidance.' }, { q: 'Which languages are supported?', a: 'My SafetyZone provides broad language support for allergy communication.' }, { q: 'What should I do before a trip?', a: 'Confirm medications, emergency plans, local healthcare information, and airline or restaurant policies before departure.' }],
  },
};

export const landingSlugs = Object.keys(landingConfigs);
