import type { LandingConfig } from './_template';

export const landingConfigs: Record<string, LandingConfig> = {
  'peanut-allergy-app': {
    slug: 'peanut-allergy-app',
    title: 'Peanut Allergy App | My SafetyZone — AI Allergen Scanner & EpiPen Tracker',
    metaDescription: 'The #1 peanut allergy app for iOS. AI-powered peanut detection in menus and recipes, QR allergy cards in 200+ languages, EpiPen expiration tracker, and FDA recall alerts. Free download.',
    h1: 'The #1 Peanut Allergy App',
    h1Accent: 'for iOS.',
    keyword: 'peanut allergy app',
    audience: 'people with peanut allergies, parents of kids with peanut allergies, and adults managing anaphylactic peanut allergies',
    intro: "Living with a peanut allergy means every meal is a calculation. My SafetyZone takes the guesswork out — AI-powered peanut detection across menus, recipes, and ingredient lists, plus a QR allergy card you can show any restaurant, anywhere in the world.",
    benefits: [
      { title: 'AI peanut detection', body: 'Scan menus, recipes, and ingredients with AI that flags peanuts, peanut oil, peanut flour, and hidden derivatives like arachis oil.' },
      { title: 'QR allergy card in 200+ languages', body: 'One scan and any restaurant — domestic or international — knows you have a peanut allergy in their native language.' },
      { title: 'EpiPen expiration tracker', body: 'Never carry an expired epinephrine auto-injector again. Auto-reminders before each EpiPen expires.' },
      { title: 'FDA recall alerts', body: 'Real-time notifications when products are recalled for undeclared peanut content.' },
    ],
    faqs: [
      { q: 'How does My SafetyZone detect peanuts?', a: 'My SafetyZone uses AI trained on FDA allergen databases and ingredient derivative lists to flag peanuts, peanut protein, peanut oil, peanut flour, arachis oil, mandelonas, and other hidden peanut sources in menus, recipes, and packaged foods.' },
      { q: 'Is My SafetyZone good for kids with peanut allergies?', a: 'Yes. Parents can build allergy profiles for each child, generate QR allergy cards for school and daycare staff, and track every EpiPen expiration date in one place.' },
      { q: 'Does it work for tree nut allergies too?', a: 'Yes. My SafetyZone supports peanuts and all tree nuts (almonds, cashews, walnuts, pecans, pistachios, macadamia, Brazil nuts, hazelnuts), plus 50+ other allergens and dietary needs.' },
      { q: 'Is My SafetyZone free?', a: 'Yes — free to download on the iOS App Store with a 7-day free trial of premium features.' },
    ],
  },
  'celiac-app': {
    slug: 'celiac-app',
    title: 'Celiac Disease App | My SafetyZone — Gluten-Free AI Scanner & Recipe AI',
    metaDescription: 'The best celiac disease app on iOS. AI-powered gluten detection in menus and ingredients, allergen-free Recipe AI, QR cards in 200+ languages for safe dining anywhere. Free download.',
    h1: 'The #1 Celiac Disease App',
    h1Accent: 'for safe gluten-free living.',
    keyword: 'celiac disease app',
    audience: 'people with celiac disease, non-celiac gluten sensitivity, and wheat allergies',
    intro: "Celiac disease isn't a preference — it's a medical condition that demands precision. My SafetyZone gives you AI-powered gluten detection, allergen-free Recipe AI, and a QR card that translates your dietary needs into 200+ languages.",
    benefits: [
      { title: 'AI gluten detection', body: 'Detects wheat, barley, rye, malt, brewer\'s yeast, and hidden gluten across menus, ingredient lists, and barcoded products.' },
      { title: 'Recipe AI with gluten-free swaps', body: 'Paste any recipe and get safe, taste-matched gluten-free substitutions that account for binding, texture, and baking ratios.' },
      { title: 'QR celiac card in 200+ languages', body: 'Show one card to communicate celiac disease — and the cross-contact rules that go with it — to staff anywhere in the world.' },
      { title: 'FDA recall alerts', body: 'Get notified instantly when products are recalled for undeclared gluten or wheat.' },
    ],
    faqs: [
      { q: 'Does My SafetyZone account for cross-contact?', a: 'Yes. The QR celiac card communicates not just gluten avoidance but the cross-contact protocols celiac requires — separate prep surfaces, dedicated fryers, and clean utensils.' },
      { q: 'Can I scan ingredient lists for hidden gluten?', a: 'Yes. AI detects wheat, barley, rye, malt, brewer\'s yeast, modified food starch, and ingredient derivatives that other apps miss.' },
      { q: 'Does Recipe AI work for gluten-free baking?', a: 'Yes. Recipe AI understands cooking chemistry — when you swap wheat flour, it adjusts binders, hydration, and ratios so your gluten-free version actually works.' },
      { q: 'Is it free?', a: 'My SafetyZone is free to download on iOS with a 7-day free trial of premium features.' },
    ],
  },
  'epipen-tracker-app': {
    slug: 'epipen-tracker-app',
    title: 'EpiPen Tracker App | My SafetyZone — Expiration Reminders & Auto-Injector Tracking',
    metaDescription: 'The best EpiPen tracker app on iOS. Track every epinephrine auto-injector, get auto-reminders before each expires, and manage inhalers and medical devices in one place. Free download.',
    h1: 'The #1 EpiPen Tracker App',
    h1Accent: 'for life-saving medication.',
    keyword: 'EpiPen tracker app',
    audience: 'anyone carrying epinephrine auto-injectors, parents managing kids\' EpiPens, and caregivers tracking multiple medical devices',
    intro: "Expired EpiPens lose potency. My SafetyZone tracks every epinephrine auto-injector you and your family carry, sends reminders before each one expires, and keeps inhalers and other medical devices on the same schedule.",
    benefits: [
      { title: 'Track every EpiPen', body: 'Add EpiPens for yourself and family members. Each one is monitored independently with its own expiration date.' },
      { title: 'Auto-reminders before expiration', body: 'Get notified weeks in advance so you can refill before your prescription lapses.' },
      { title: 'Inhaler & medical device tracking', body: 'Track albuterol inhalers, AUVI-Q, glucagon, and any other expiring medical device on the same dashboard.' },
      { title: 'Built into a complete allergy app', body: 'Pair EpiPen tracking with QR allergy cards, AI menu scanning, and FDA recall alerts.' },
    ],
    faqs: [
      { q: 'How early do reminders fire?', a: 'Reminders are sent weeks before expiration so you have time to refill your prescription before your current EpiPen lapses.' },
      { q: 'Can I track EpiPens for my whole family?', a: 'Yes. Add an EpiPen for each family member with its own expiration date and individual reminders.' },
      { q: 'Does it track other auto-injectors?', a: 'Yes — EpiPen, AUVI-Q, generic epinephrine auto-injectors, and any other medical device with an expiration date.' },
      { q: 'Is it free?', a: 'My SafetyZone is free to download on iOS. EpiPen tracking is included.' },
    ],
  },
  'qr-allergy-card': {
    slug: 'qr-allergy-card',
    title: 'QR Allergy Card App | My SafetyZone — Translated into 200+ Languages',
    metaDescription: 'The best QR allergy card app. Generate a personal QR code that communicates your food allergies in 200+ languages — perfect for restaurants, travel, and dining out. Free on iOS.',
    h1: 'QR Allergy Cards',
    h1Accent: 'in 200+ languages.',
    keyword: 'QR allergy card',
    audience: 'people who travel internationally, eat out frequently, or need to communicate complex allergies to non-English-speaking staff',
    intro: "Saying \"I have a peanut allergy\" in Japanese, Thai, or Italian shouldn't be a barrier to eating safely. My SafetyZone generates a QR code that contains your full allergy profile, instantly translated into the local language at any restaurant — anywhere in the world.",
    benefits: [
      { title: '200+ languages, auto-translated', body: 'When staff scans your QR card, it appears in their language. No app required on their end — just a phone camera.' },
      { title: 'Cross-contact instructions included', body: 'Communicate not just allergens but the protocols you need — clean prep surfaces, dedicated fryers, no shared utensils.' },
      { title: 'Travel-ready', body: 'Pair with Travel Allergen guides for destination-specific safety tips and local allergen databases.' },
      { title: 'Always up to date', body: 'Update your allergy profile in the app; the QR card auto-updates. No reprinting cards.' },
    ],
    faqs: [
      { q: 'Do restaurants need a special app to scan it?', a: 'No. Any phone camera or QR reader scans the card and opens a translated allergy summary in their browser.' },
      { q: 'Which languages are supported?', a: 'My SafetyZone supports 200+ languages, including Spanish, French, German, Italian, Japanese, Mandarin, Korean, Arabic, Hindi, Portuguese, Thai, Vietnamese, and many more.' },
      { q: 'Can I print it as a physical card?', a: 'Yes. You can print or save your QR card to your phone\'s wallet for quick access without unlocking the app.' },
      { q: 'Is it free?', a: 'Yes — QR Allergy Cards are included free with My SafetyZone on iOS.' },
    ],
  },
  'gluten-free-app': {
    slug: 'gluten-free-app',
    title: 'Gluten Free App | My SafetyZone — AI Gluten Scanner & Safe Recipe Finder',
    metaDescription: 'The #1 gluten free app on iOS. AI-powered gluten detection, allergen-free Recipe AI, QR cards in 200+ languages, and FDA recall alerts. Built for celiac and gluten sensitivity. Free download.',
    h1: 'The #1 Gluten Free App',
    h1Accent: 'for safe eating.',
    keyword: 'gluten free app',
    audience: 'anyone living gluten-free — celiac, gluten-sensitive, or by choice',
    intro: "Whether you're celiac, gluten-sensitive, or gluten-free by choice, My SafetyZone makes safe eating effortless. AI detects gluten in menus and ingredients, Recipe AI swaps in safe substitutions, and your QR card communicates your needs in 200+ languages.",
    benefits: [
      { title: 'AI gluten scanning', body: 'Detect wheat, barley, rye, malt, and hidden gluten in menus, recipes, and ingredient lists.' },
      { title: 'Gluten-free Recipe AI', body: 'Paste any recipe and get safe, tasty gluten-free substitutions that respect baking chemistry.' },
      { title: 'Travel allergen guides', body: 'Destination-specific gluten safety guides for international and domestic travel.' },
      { title: 'FDA recall alerts', body: 'Real-time notifications when products are recalled for undeclared gluten.' },
    ],
    faqs: [
      { q: 'Is it built for celiac disease?', a: 'Yes — My SafetyZone takes celiac seriously, including cross-contact protocols and the precision celiac requires.' },
      { q: 'Can I scan packaged food barcodes?', a: 'Barcode allergen scanning is rolling out. AI ingredient analysis, menu scanning, and Recipe AI are live today.' },
      { q: 'Does it work for non-celiac gluten sensitivity?', a: 'Yes. Customize your profile to flag gluten, wheat, or both — whichever applies to you.' },
      { q: 'Is it free?', a: 'Free to download on iOS with a 7-day free trial of premium features.' },
    ],
  },
  'food-allergy-app-for-kids': {
    slug: 'food-allergy-app-for-kids',
    title: 'Food Allergy App for Kids | My SafetyZone — School-Ready QR Cards & EpiPen Reminders',
    metaDescription: 'The best food allergy app for kids and parents. Allergy profiles for each child, school-ready QR cards in 200+ languages, EpiPen expiration reminders, and FDA recall alerts. Free on iOS.',
    h1: 'Food Allergy App',
    h1Accent: 'built for kids and parents.',
    keyword: 'food allergy app for kids',
    audience: 'parents managing food allergies for one or more children, caregivers, and grandparents',
    intro: "Managing a child's food allergy is a full-time job. My SafetyZone gives parents one place to track every allergy, every EpiPen, and every meal — plus QR cards that schools, daycares, and restaurants can scan instantly.",
    benefits: [
      { title: 'Profile per child', body: 'Each child gets their own allergy profile, QR card, and EpiPen tracker.' },
      { title: 'School & daycare ready', body: 'Print or share QR cards with teachers, nurses, and caregivers — translated into the school\'s language.' },
      { title: 'EpiPen reminders', body: 'Never get caught with an expired auto-injector. Reminders fire weeks before each one expires.' },
      { title: 'FDA recall alerts', body: 'Real-time notifications protect your family from recalled products with undeclared allergens.' },
    ],
    faqs: [
      { q: 'Can I manage multiple kids?', a: 'Yes. Add a profile for each child with their own allergens, EpiPens, and QR card.' },
      { q: 'Is it safe for the child to use?', a: 'Most parents manage the app themselves and share QR cards with the child or their caregivers. The app uses encrypted health data storage.' },
      { q: 'How does it help with school?', a: 'Generate a QR card the school nurse, teachers, and cafeteria staff can scan. It includes allergens, severity, EpiPen location, and emergency contacts.' },
      { q: 'Is it free?', a: 'Yes — free on iOS with a 7-day free trial of premium features.' },
    ],
  },
};

export const landingSlugs = Object.keys(landingConfigs);
